application: cedar-dogfish-832
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /admin/.*
  script: view.py
  login: admin
- url: /static
  static_dir: static
- url: .*
  script: main.application
libraries:
- name: django
  version: "latest"

env_variables:
  DJANGO_SETTINGS_MODULE: 'djangoguestbook.settings'